In [1]:
import os
os.chdir("..//src")

In [2]:
from pre import *

In [3]:
case = Case(1.0, 0.0)

In [4]:
w_inf = case.w_inf

In [6]:
w_inf

array([1.4, 1.4, 0. , 3.2])

In [12]:
W0 = np.zeros([5306, 4])
for j in range(5306):
    W0[j] = w_inf
    pass

In [15]:
W0

array([[1.4, 1.4, 0. , 3.2],
       [1.4, 1.4, 0. , 3.2],
       [1.4, 1.4, 0. , 3.2],
       ...,
       [1.4, 1.4, 0. , 3.2],
       [1.4, 1.4, 0. , 3.2],
       [1.4, 1.4, 0. , 3.2]])

In [1]:
import numpy as np

In [2]:
a = np.random.randn(3, 4)

In [3]:
a

array([[ 0.29404894,  0.23478247, -0.12065651,  0.58714585],
       [-0.23425757, -0.78728021, -0.93443439,  1.48093295],
       [-0.6311326 ,  0.58686246,  1.2173562 ,  1.23528957]])

In [6]:
a[1]

array([-0.23425757, -0.78728021, -0.93443439,  1.48093295])

In [5]:
a[1]

array([-0.23425757, -0.78728021, -0.93443439,  1.48093295])